In [2]:
# Task 1: Create and Explore Arrays
# Create a NumPy array of numbers from 1 to 20.
# Print:
# Shape
# Size
# Data type
# Number of dimensions

import numpy as np

ar1 = np.array([10,2,45,67,89,53,63,95])
print(ar1.shape)
print(ar1.size)
print(ar1.dtype)
print(ar1.ndim)

(8,)
8
int64
1


In [2]:
# Task 2: Array Operations

# Create two arrays:

# a = [10,20,30,40,50]
# b = [1,2,3,4,5]

# Perform:

# Addition
# Subtraction
# Multiplication
# Division
# Power (a²)

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[       10       400     27000   2560000 312500000]


In [5]:
# Task 3: Student Marks Analysis

# Create an array of marks:

# [78, 85, 90, 65, 88, 92, 74, 81]

# Find:

#     Maximum marks
#     Minimum marks
#     Average marks
#     Sum of marks
#     Standard deviation

ar = np.array([78, 85, 90, 65, 88, 92, 74, 81])
print(max(ar))
print(min(ar))
# print(ar.avg())
print(sum(ar))
print(np.std(ar))

92
65
653
8.499080832654787


In [9]:
# Task 4: Reshape Array
#     Create an array from 1 to 24.
#     Convert it into:
#     4 × 6 matrix
#     6 × 4 matrix
#     2 × 3 × 4 array

arr = np.array([i for i in range(1,25)])
print(arr.reshape((4,6)))
print()
print(arr.reshape((6,4)))
print()
print(arr.reshape((2,3,4)))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
# Task 5: Slicing Practice

# Create:

# arr = np.arange(1,26)

# Print:

#     First 10 elements
#     Last 5 elements
#     Elements from index 5 to 15
#     Alternate elements
#     Reverse array

arr = np.arange(1,26)
print(arr[:10])
print()
print(arr[-1:-6:-1])
print()
print(arr[5:15])
print()
print(arr[::2])
print()
print(arr[::-1])

[ 1  2  3  4  5  6  7  8  9 10]

[25 24 23 22 21]

[ 6  7  8  9 10 11 12 13 14 15]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


In [24]:
# Task 6: Matrix Operations

# Create two 3×3 matrices.

# Perform:

# Matrix Addition
# Matrix Subtraction
# Matrix Multiplication
# Transpose
# Determinant

ar1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,10]])
ar2 = np.full((3,3),6,dtype="int64")
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(np.linalg.inv(ar1))
print(np.linalg.det(ar1))

[[ 7  8  9]
 [10 11 12]
 [13 14 16]]
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  4]]
[[ 6 12 18]
 [24 30 36]
 [42 48 60]]
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
-2.9999999999999996


In [31]:
# Task 7: Random Data Analysis

# Generate 100 random integers between 1 and 100.

# Find:

# Maximum value
# Minimum value
# Mean
# Median
# Count of numbers greater than 50

a = np.random.randint(1,100,100)
print(a)

print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))

count = len(arr[arr>50])
print(count)


[47 94 84 13 61 43  4 86 19 97 13 77 77 11 32 82  5 79 36 14 44 88 92 32
 30 99 49 71 18 21  8 91 59 14 15 12  2 26 91 82 38 27 70 78 37 64 94 85
 14 24 28  3 18 12 13 92 86 33 39 76 12 30 44 46 53  5 52 81 38 30 82 15
 14  8 53 26 91 36  3 94 57  2 69  3 29 57 62 62 11 80 84 15 36 94 37 55
 36 14 78 76]
99
2
46.19
38.5
0


In [38]:
# Task 8: Employee Salary Analysis

# Salary data:

# [25000, 30000, 45000, 50000, 35000, 60000, 70000]

# Find:

# Average salary
# Highest salary
# Lowest salary
# Salaries above average
# Increase all salaries by 10%

salary = np.array([25000, 30000, 45000, 50000, 35000, 60000, 70000])
mean = np.mean(salary)
print(mean)
print(np.max(salary))
print(np.min(salary))
print(salary[mean>salary])
salary = salary+salary*(10/100)
print(salary)


45000.0
70000
25000
[25000 30000 35000]
[27500. 33000. 49500. 55000. 38500. 66000. 77000.]


In [40]:
# Task 9: Search and Filter

# Create:

# arr = np.array([12,25,37,48,50,63,75,80])

# Find:

# Index of value 50
# All values greater than 40
# Even numbers
# Odd numbers
# Values divisible by 5

arr = np.array([12,25,37,48,50,63,75,80])
print(np.where(arr==50))
print(arr[arr>40])
print(np.where(arr%2==0))
print(np.where(arr%2==1))
print(np.where(arr%5==0))

(array([4]),)
[48 50 63 75 80]
(array([0, 3, 4, 7]),)
(array([1, 2, 5, 6]),)
(array([1, 4, 6, 7]),)


In [4]:
# Task 10: Mini Sales Analysis Project

# A company has monthly sales:

# sales = [45000,52000,48000,61000,59000,72000,
#          68000,75000,80000,77000,85000,90000]

# Find:

# Total yearly sales
# Average monthly sales
# Highest sales 
# Lowest sales 
# sales above average
# Percentage growth from first month to last month

sales = [45000,52000,48000,61000,59000,72000,
         68000,75000,80000,77000,85000,90000]
print(np.sum(sales))
mean = np.mean(sales)
print(mean)
print(np.max(sales))
print(np.min(sales))
# print(sales[sales < mean])

812000
67666.66666666667
90000
45000


In [8]:
# Task 12: Stack Arrays
# Create two 2×3 arrays and perform:

# vstack()
# hstack()
# concatenate()
# dstack()


a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])

np.hstack((a1,a2))
np.vstack((a1,a2))
result = np.concatenate((a1,a2))
print(result)

np.dstack((a1,a2))

[1 2 3 4 6 7 8 9]


array([[[1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

In [3]:
# Task 13: Sorting and Unique Values

# Given:

# [5,8,2,5,9,1,8,3,2,7]

# Find:

# Sorted array
# Unique values
# Frequency of each value
# Second largest number

arr = np.array([5,8,2,5,9,1,8,3,2,70])
print(np.unique(arr))
print(np.sort(arr))
print(np.searchsorted(arr, 10))

[ 1  2  3  5  8  9 70]
[ 1  2  2  3  5  5  8  8  9 70]
9


In [4]:
# Task 14: Weather Data Analysis

# Temperature data for 30 days:
# Generate random temperatures between 20°C and 45°C.
# Find:
#     Hottest day
#     Coldest day
#     Average temperature
#     Days above 35°C
#     Days below 25°C


temp = np.random.randint(20,45,30)
print(temp.max()+1)
print(temp.min()+1)
np.mean(temp)

temp[temp>35]

temp[temp<25]

45
21


array([24, 20, 22, 23, 24, 20, 20], dtype=int32)

In [11]:
# Task 15: Complete NumPy Challenge

# Create a dataset of 500 students' marks using random numbers.

# Calculate:

# Top 10 marks
# Bottom 10 marks
# Average marks
# Students scoring above 75
# Students scoring below 35
# Pass percentage
# Grade distribution (A, B, C, D, F)

marks = np.random.randint(30,100,500)
marks

array([48, 36, 52, 55, 78, 35, 74, 50, 77, 96, 47, 86, 91, 40, 81, 73, 57,
       74, 54, 78, 78, 68, 49, 84, 80, 33, 90, 70, 80, 53, 52, 43, 31, 38,
       30, 36, 71, 61, 70, 71, 38, 44, 89, 99, 33, 37, 98, 59, 71, 47, 49,
       37, 45, 76, 72, 61, 90, 60, 42, 58, 85, 90, 82, 38, 46, 81, 81, 91,
       76, 95, 60, 47, 52, 66, 52, 63, 32, 51, 81, 37, 76, 45, 91, 66, 75,
       78, 47, 86, 35, 83, 35, 70, 46, 40, 42, 47, 76, 81, 44, 38, 67, 67,
       78, 67, 77, 67, 65, 47, 67, 99, 73, 35, 74, 31, 59, 64, 80, 30, 43,
       60, 38, 94, 75, 97, 98, 39, 90, 47, 64, 62, 48, 45, 83, 88, 73, 87,
       99, 33, 66, 34, 65, 58, 73, 79, 60, 49, 61, 99, 81, 57, 84, 74, 71,
       54, 89, 88, 37, 83, 80, 76, 49, 92, 69, 91, 45, 68, 78, 36, 61, 36,
       43, 93, 96, 39, 96, 81, 30, 59, 64, 63, 64, 63, 69, 78, 82, 93, 77,
       78, 54, 58, 80, 87, 84, 56, 76, 51, 79, 81, 92, 54, 45, 92, 60, 66,
       46, 65, 80, 93, 30, 90, 83, 35, 97, 58, 39, 71, 34, 55, 52, 55, 66,
       48, 65, 46, 68, 81

In [12]:
print(np.sort(marks)[-10:])
print()
print(np.sort(marks)[:11])
print(marks[marks>75])
print(marks[marks<35])

pass_per = (np.sum(marks>=35) / len(marks)) * 100
print(pass_per)

[98 98 98 98 99 99 99 99 99 99]

[30 30 30 30 30 30 30 31 31 31 31]
[78 77 96 86 91 81 78 78 84 80 90 80 89 99 98 76 90 85 90 82 81 81 91 76
 95 81 76 91 78 86 83 76 81 78 77 99 80 94 97 98 90 83 88 87 99 79 99 81
 84 89 88 83 80 76 92 91 78 93 96 96 81 78 82 93 77 78 80 87 84 76 79 81
 92 92 80 93 90 83 97 81 84 76 90 76 86 91 95 98 90 97 81 91 89 98 83 94
 88 91 80 93 87 95 83 92 84 86 92 84 97 90 86 96 82 94 83 86 87 82 95 95
 90 98 83 92 82 78 91 97 84 87 76 81 98 80 92 86 79 77 94 86 88 76 79 78
 84 96 91 87 80 84 87 76 89 85 86 90 89 84 99 95 89 94 82 92 96 85 93 85
 76 84 82 93 84 76 99 98 94 76 87 81 88 87]
[33 31 30 33 32 31 30 33 34 30 30 34 34 31 30 30 31 33 32 33 30 32 32 31
 32 32 34]
94.6


In [9]:
# grade distribution

A = np.sum(marks>95)
B = np.sum((marks<95) & (marks>85))
C = np.sum((marks<85) & (marks>75))
D = np.sum((marks<75) & (marks>65))
E = np.sum((marks<65) & (marks>55))
F  = np.sum(marks <55)

In [13]:
print("count of students : ")
print("Grade A : ",A)
print("Grade B : ",B)
print("Grade C : ",C)
print("Grade D : ",D)
print("Grade E : ",E)
print("Grade F : ",F)

count of students : 
Grade A :  32
Grade B :  75
Grade C :  76
Grade D :  66
Grade E :  62
Grade F :  152
