In [1]:
# numpy library
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
ar = np.zeros((2,3))
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
ar1 = np.full((4,5),10)
print(ar1)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [7]:
ar2 = np.arange(10,30,1)
print(ar2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [ ]:
# Property
# ndim = (It check dimention of array)
# shape - returns number of rows and column
# size - returns number of element
# dtype - returns datatype

In [ ]:
## function of array
# zeros(shape,dtype)
# ones(shape,dtype)
# full(shape,fill_value,dtype)
# eye - it creates identity matrix
# arange(start,end,step) - it works like range datatype