In [ ]:
# numpy library
import numpy as np

In [ ]:
a0 = np.array(45)
a1 = np.array([34,67,89])
a2 = np.array([[1,2,3],[5,6,7],[3,7,9]])
a3 = np.array([[[1,2,3],[6,7,8]],[[9,6,4],[2,5,8]]])

In [ ]:
# Indexing
print(a1[1])

67


In [ ]:
print(a2)
print()
print(a2[1])
print()
print(a2[1][2])

[[1 2 3]
 [5 6 7]
 [3 7 9]]

[5 6 7]

7


In [ ]:
print(a3)
print()
print(a3[1])
print()
print(a3[1][1])
print()
print(a3[1][1][2])

[[[1 2 3]
  [6 7 8]]

 [[9 6 4]
  [2 5 8]]]

[[9 6 4]
 [2 5 8]]

[2 5 8]

8


In [ ]:
# alternative way
print(a3[1,1,2])
print(a3[1][1][2])

8
8


In [ ]:
# Slicing
a1 = np.array([1,2,3,4,5,6,7,8])
print(a1[2:6:2])
print(a1[2:6])# step value = 1
print(a1[:5]) # start with 0
print(a1[3::1]) # end at -1

[3 5]
[3 4 5 6]
[1 2 3 4 5]
[4 5 6 7 8]


In [ ]:
a3 = np.array([[11,22,33,44,55],[1,2,3,4,5],[12,12,12,12,12]])

In [ ]:
print(a3)
print()
print(a3[1,1:3])
print()
print(a3[0,-2:0:-1])

In [ ]:
# Arithmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([8,7,6,5,4])

print(a1+a2)
print(a1*a2)
print(a1/a2)

In [ ]:
# Aggrigate function
np.sum(a1)
np.min(a1)
np.max(a1)
np.std(a1)

In [ ]:
# reshape - change dimentions
print(a1)
a = a1.reshape((2,4))

In [ ]:
# flatten() - convert multi-dimentional array to one dimentional array -- retrun copy                                                                                                                                                                                                   -- deep copy
# ravel() - convert multi-dimentional array to one dimentional array -- return view -- shallow copy
# copy() -- deep copy
# view() -- create only view
a = a2.flatten()
print(a)
a[1] = 999
print(a)
print(a1)

In [ ]:
a = a2.ravel()
print(a)
a[1] = 999
print(a)
print(a1)

In [ ]:
# Join two or more array using 
# 1) concatenate()
# stack() - axis=0 (row wise) -- axis=1 (column wise)

a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])

np.stack((a1,a2),axis=0)

In [ ]:
np.stack((a1,a2),axis=1)

In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([6,7,8,9])

np.hstack((a1,a2))
np.vstack((a1,a2))

In [ ]:
# Where function -- it returns index number
a = np.array([12,24,45,67,78,90,86])
index = np.where(a>50) # returns index number
a[index] # access element by index number

In [ ]:
a = np.array([12,24,45,67,78,90,86])
print(a[np.where(a%3==0)])
print(a[np.where(a%5==0)])
print(a[np.where((a%3==0) & (a%5==0))])

In [ ]:
marks = np.array([12,24,45,67,78,90,86])
np.where(marks>40,"Pass","Fail")